// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Person = __t.object("Person", {
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const StudyGroup = __t.object("StudyGroup", {
  id: __t.u64(),
  name: __t.string(),
});
export type StudyGroup = __Infer<typeof StudyGroup>;

export const User = __t.object("User", {
  id: __t.identity(),
  clerkId: __t.string(),
  name: __t.option(__t.string()),
  email: __t.option(__t.string()),
  role: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UserGroup = __t.object("UserGroup", {
  id: __t.u64(),
  userId: __t.identity(),
  groupId: __t.u64(),
});
export type UserGroup = __Infer<typeof UserGroup>;

