import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ClerkTokenProvider } from "@/app/ClerkTokenProvider";
import { Providers } from "@/app/providers";
import "@/app/globals.css";
import Footer from "@/app/Components/Footer";
import Header from "@/app/Components/Header";
import FloatingChat from "@/app/Components/FloatingChat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AIGuidebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="no" className="" data-theme="">
        <head>
          <title>AI Guide Book</title>
        </head>

        <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
          <ClerkTokenProvider>
            <Providers>
              <Header />
              <main className="flex-1 w-full flex flex-col">{children}</main>
              <Footer />
              <FloatingChat />
            </Providers>
          </ClerkTokenProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
