// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReducer from "../add_reducer";
import CreateChatInviteReducer from "../create_chat_invite_reducer";
import CreateChatSessionReducer from "../create_chat_session_reducer";
import CreateCourseReducer from "../create_course_reducer";
import CreateCourseTaskReducer from "../create_course_task_reducer";
import CreateTaskGroupReducer from "../create_task_group_reducer";
import GradeTaskSubmissionReducer from "../grade_task_submission_reducer";
import InviteUserToChatReducer from "../invite_user_to_chat_reducer";
import JoinChatWithInviteCodeReducer from "../join_chat_with_invite_code_reducer";
import JoinCourseReducer from "../join_course_reducer";
import JoinTaskGroupReducer from "../join_task_group_reducer";
import LeaveChatSessionReducer from "../leave_chat_session_reducer";
import LeaveCourseReducer from "../leave_course_reducer";
import LeaveTaskGroupReducer from "../leave_task_group_reducer";
import RemoveChatSessionReducer from "../remove_chat_session_reducer";
import SaveChatMessageReducer from "../save_chat_message_reducer";
import SayHelloReducer from "../say_hello_reducer";
import SetUserProfileReducer from "../set_user_profile_reducer";
import SetUserRoleReducer from "../set_user_role_reducer";
import SubmitTaskGroupWorkReducer from "../submit_task_group_work_reducer";

export type AddParams = __Infer<typeof AddReducer>;
export type CreateChatInviteParams = __Infer<typeof CreateChatInviteReducer>;
export type CreateChatSessionParams = __Infer<typeof CreateChatSessionReducer>;
export type CreateCourseParams = __Infer<typeof CreateCourseReducer>;
export type CreateCourseTaskParams = __Infer<typeof CreateCourseTaskReducer>;
export type CreateTaskGroupParams = __Infer<typeof CreateTaskGroupReducer>;
export type GradeTaskSubmissionParams = __Infer<typeof GradeTaskSubmissionReducer>;
export type InviteUserToChatParams = __Infer<typeof InviteUserToChatReducer>;
export type JoinChatWithInviteCodeParams = __Infer<typeof JoinChatWithInviteCodeReducer>;
export type JoinCourseParams = __Infer<typeof JoinCourseReducer>;
export type JoinTaskGroupParams = __Infer<typeof JoinTaskGroupReducer>;
export type LeaveChatSessionParams = __Infer<typeof LeaveChatSessionReducer>;
export type LeaveCourseParams = __Infer<typeof LeaveCourseReducer>;
export type LeaveTaskGroupParams = __Infer<typeof LeaveTaskGroupReducer>;
export type RemoveChatSessionParams = __Infer<typeof RemoveChatSessionReducer>;
export type SaveChatMessageParams = __Infer<typeof SaveChatMessageReducer>;
export type SayHelloParams = __Infer<typeof SayHelloReducer>;
export type SetUserProfileParams = __Infer<typeof SetUserProfileReducer>;
export type SetUserRoleParams = __Infer<typeof SetUserRoleReducer>;
export type SubmitTaskGroupWorkParams = __Infer<typeof SubmitTaskGroupWorkReducer>;

